language: python

sudo: false

python:
    - "3.3"

services:
    - elasticsearch

install: pip install -r requirements/testing.txt

before_install:
    - echo "Fetching and installing BLAST"
    - wget ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-x64-linux.tar.gz
    - tar -zxvf ncbi-blast-2.2.30+-x64-linux.tar.gz | tail
    - export PATH="${TRAVIS_BUILD_DIR}/ncbi-blast-2.2.30+/bin:$PATH"

script: make coverage

after_success: coveralls
