language: python

sudo: required

services:
  - postgresql

python:
    - "3.5"
    - "3.6"

before_script:
    - sleep 10

install: pip install -r requirements/testing.txt

before_install:
    - echo "Fetching and installing BLAST"
    - apt-get install ncbi-blast+
    - psql -c 'create database travis_ci_test;' -U postgres

script: make coverage

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
