language: python

sudo: required

services:
  - postgresql

python:
  - "3.5"
  - "3.6"

before_script:
    - sleep 10

install: pip install -r run/requirements.txt

before_install:
    - echo "Fetching and installing BLAST"
    - sudo apt-get install ncbi-blast+
    - psql -c 'create database travis_ci_test;' -U postgres

script: make coverage_travis

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
